[Settings]
# 🎯 强制关联你刚刚建立的 21 国全量豪华菜单
source_file = config/user_demo.txt

# 🎯 将最终的清洗结果，精准吐到对应的 output 文件中
final_file = output/user_result.txt

# 🚀 跨国流免误杀高容错配置：把刺探超时放宽到 8-10 秒
timeout = 8
open_url_info = False
ipv6_support = False
